# Generated by Django 3.0.8 on 2020-09-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('datess', models.CharField(max_length=120)),
                ('linkss', models.CharField(default='notpresent', max_length=120)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('institute_name', models.CharField(max_length=120)),
                ('institute_city', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'news',
                'ordering': ['-entry_date'],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hits', models.IntegerField(default=0)),
            ],
        ),
    ]
