# Generated by Django 3.0.8 on 2020-09-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, upload_to='Edu_News'),
        ),
        migrations.AddField(
            model_name='news',
            name='summary',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
