# Generated by Django 3.0.8 on 2020-08-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200810_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='datess',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
