# Generated by Django 3.0.8 on 2020-08-11 20:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20200811_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='entry_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
