# Generated by Django 3.0.8 on 2020-08-13 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_news_entry_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-entry_date'], 'verbose_name_plural': 'news'},
        ),
    ]
