# Generated by Django 3.0.8 on 2020-08-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20200813_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='Insitute_city',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='institute_name',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
