# Generated by Django 3.0.8 on 2020-09-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20200815_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='Institute_city',
        ),
        migrations.AddField(
            model_name='news',
            name='institute_city',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
